### ISSUE TITLE
No module named 'learning.auxiliary_objective'

### ISSUE THREAD

**Issue by vincentlux** [clic-lab/ciff#10]
Hi, 

Thank you for releasing the code! I tried to reproduce the Chai dataset experiment, however got this error:

```
$ python3 src/experiments_house/train_goal_prediction_from_disk.py
Traceback (most recent call last):
  File "src/experiments_house/train_goal_prediction_from_disk.py", line 13, in <module>
    from learning.single_client.goal_prediction_house_single_360_image_supervised_from_disk import \
  File "/home/xiaopen2/proj/indoor_nav/reproduce/ciff/src/learning/single_client/goal_prediction_house_single_360_image_supervised_from_disk.py", line 15, in <module>
    from learning.auxiliary_objective.goal_prediction import GoalPrediction
ModuleNotFoundError: No module named 'learning.auxiliary_objective'
```
It seems like the package does not have `auxiliary_objective` module? Thank you very much for your help!

**Comment by dkmisra** [comment]
That package is no longer needed and I need to remove the dependence on that package from all files. Unfortunately, the development and release of production code is currently stalled. I should have time over Christmas break to focus on this. I apologize for the inconvenience.

**Comment by vincentlux** [comment]
Thank you very much!

**Comment by anirban-code-to-live** [comment]
The bug still persists. It'd be great if you could fix this or tell me a work-around for this.

**Comment by ilkerkesen** [comment]
This bug still exists. I want to reproduce the results. Could you please make this work reproducible by fixing this issue? Thanks.
